version: '3.7'

services:
  db:
    image: postgres:11
    restart: always
    container_name: datamart-postgres
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=wikidata
    volumes:
        - postgres:/var/lib/postgresql/data
        - ./data/postgres/uaz.sql.gz:/docker-entrypoint-initdb.d/01-uaz.sql.gz
        - ./data/postgres:/backup
    ports:
        - "5433:5432"

# Use internal Docker presistent volumes for Postgres storage, as Windows is having issues with mounting
# local folders as Postgres data folders

volumes:
    postgres:
        name: datamart-postgres-volume