version: '3.7'

services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    restart: always
    container_name: blazegraph
    volumes:
      - ./data/blaze-graph:/data
      - ./data/import:/import
    ports:
      - "8999:8080"

