version: '3.7'

services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    restart: always
    container_name: datamart-blazegraph
    volumes:
      - ./data/blaze-graph:/external
      - ./data/blaze-graph/RWStore.properties:/RWStore.properties
    ports:
      - "9999:8080"

  db:
    image: postgres:11
    restart: always
    container_name: datamart-postgres
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=wikidata
    volumes:
        - postgres:/var/lib/postgresql/data
        - ./data/postgres/import/uaz.sql:/docker-entrypoint-initdb.d/01-uaz.sql
    ports:
        - "5433:5432"

# Use internal Docker presistent volumes for Postgres storage, as Windows is having issues with mounting
# local folders as Postgres data folders

volumes:
    postgres:
        name: datamart-postgres-volume